-- MySQL Script generated by MySQL Workbench
-- Sat Dec  4 18:37:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nanocovax
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nanocovax` ;

-- -----------------------------------------------------
-- Schema nanocovax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nanocovax` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `nanocovax` ;

-- -----------------------------------------------------
-- Table `nanocovax`.`tinhthanhpho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`tinhthanhpho` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`tinhthanhpho` (
  `matp` CHAR(3) NOT NULL,
  `ten` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`quanhuyen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`quanhuyen` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`quanhuyen` (
  `maqh` CHAR(3) NOT NULL,
  `ten` VARCHAR(45) NOT NULL,
  `matp` CHAR(3) NOT NULL,
  PRIMARY KEY (`maqh`),
  INDEX `qh_tp_idx` (`matp` ASC) VISIBLE,
  CONSTRAINT `qh_tp`
    FOREIGN KEY (`matp`)
    REFERENCES `nanocovax`.`tinhthanhpho` (`matp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`taikhoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`taikhoan` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`taikhoan` (
  `id` VARCHAR(13) NOT NULL,
  `password` CHAR(32) NULL DEFAULT NULL,
  `phanquyen` VARCHAR(9) NOT NULL,
  `tinhtrang` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`xaphuong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`xaphuong` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`xaphuong` (
  `maxp` CHAR(5) NOT NULL,
  `ten` VARCHAR(45) NOT NULL,
  `maqh` CHAR(3) NOT NULL,
  PRIMARY KEY (`maxp`),
  INDEX `xp_qh_idx` (`maqh` ASC) VISIBLE,
  CONSTRAINT `xp_qh`
    FOREIGN KEY (`maqh`)
    REFERENCES `nanocovax`.`quanhuyen` (`maqh`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`ttnguoidung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`ttnguoidung` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`ttnguoidung` (
  `id` VARCHAR(12) NOT NULL,
  `hoten` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ngaysinh` DATETIME NOT NULL,
  `tinhtp` CHAR(3) NOT NULL,
  `quanhuyen` CHAR(3) NOT NULL,
  `xaphuong` CHAR(5) NOT NULL,
  `sodu` INT NULL DEFAULT NULL,
  `sono` INT NULL DEFAULT NULL,
  `trangthai` CHAR(2) NOT NULL,
  `ndt` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `nd_xp_idx` (`xaphuong` ASC) VISIBLE,
  INDEX `nd_qh_idx` (`quanhuyen` ASC) VISIBLE,
  INDEX `nd_tp_idx` (`tinhtp` ASC) VISIBLE,
  CONSTRAINT `nd_qh`
    FOREIGN KEY (`quanhuyen`)
    REFERENCES `nanocovax`.`quanhuyen` (`maqh`),
  CONSTRAINT `nd_tk`
    FOREIGN KEY (`id`)
    REFERENCES `nanocovax`.`taikhoan` (`id`),
  CONSTRAINT `nd_tp`
    FOREIGN KEY (`tinhtp`)
    REFERENCES `nanocovax`.`tinhthanhpho` (`matp`),
  CONSTRAINT `nd_xp`
    FOREIGN KEY (`xaphuong`)
    REFERENCES `nanocovax`.`xaphuong` (`maxp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`hoadon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`hoadon` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`hoadon` (
  `sohd` CHAR(11) NOT NULL,
  `nguoimua` VARCHAR(12) NOT NULL,
  `thoigian` DATETIME NOT NULL,
  `tongtien` INT NULL DEFAULT NULL,
  `tratruoc` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sohd`),
  INDEX `hd_nd_idx` (`nguoimua` ASC) VISIBLE,
  CONSTRAINT `hd_nd`
    FOREIGN KEY (`nguoimua`)
    REFERENCES `nanocovax`.`ttnguoidung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`nhuyeupham`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`nhuyeupham` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`nhuyeupham` (
  `id_nyp` CHAR(5) NOT NULL,
  `tengoi` VARCHAR(45) NOT NULL,
  `thoihan` DATETIME NULL DEFAULT NULL,
  `dongia` INT NULL DEFAULT NULL,
  `gioihan` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_nyp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`cthd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`cthd` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`cthd` (
  `sohd` CHAR(11) NOT NULL,
  `soluong` INT NOT NULL,
  `id_nyp` CHAR(5) NOT NULL,
  PRIMARY KEY (`sohd`),
  INDEX `cthd_nyp_idx` (`id_nyp` ASC) VISIBLE,
  CONSTRAINT `cthd_hd`
    FOREIGN KEY (`sohd`)
    REFERENCES `nanocovax`.`hoadon` (`sohd`),
  CONSTRAINT `cthd_nyp`
    FOREIGN KEY (`id_nyp`)
    REFERENCES `nanocovax`.`nhuyeupham` (`id_nyp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`noidieutri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`noidieutri` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`noidieutri` (
  `id_ndt` INT NOT NULL auto_increment,
  `ten` VARCHAR(45) NULL DEFAULT NULL,
  `succhua` INT NULL DEFAULT NULL,
  `dangchua` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ndt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`lichsundt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`lichsundt` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`lichsundt` (
  `id` VARCHAR(12) NOT NULL,
  `thoigian` DATETIME NOT NULL,
  `id_ndt` INT NOT NULL,
  PRIMARY KEY (`id`, `thoigian`, `id_ndt`),
  INDEX `lsndt_ndt_idx` (`id_ndt` ASC) VISIBLE,
  CONSTRAINT `lsndt_nd`
    FOREIGN KEY (`id`)
    REFERENCES `nanocovax`.`ttnguoidung` (`id`),
  CONSTRAINT `lsndt_ndt`
    FOREIGN KEY (`id_ndt`)
    REFERENCES `nanocovax`.`noidieutri` (`id_ndt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`lichsunql`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`lichsunql` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`lichsunql` (
  `id_nql` VARCHAR(13) NOT NULL,
  `thoigian` DATETIME NOT NULL,
  `hoatdong` VARCHAR(20) NOT NULL,
  `id` VARCHAR(12) NULL DEFAULT NULL,
  `id_nyp` CHAR(5) NULL DEFAULT NULL,
  `id_ndt` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_nql`, `thoigian`, `hoatdong`),
  INDEX `lsnql_nd_idx` (`id` ASC) VISIBLE,
  INDEX `lsnql_nyp_idx` (`id_nyp` ASC) VISIBLE,
  INDEX `lsnql_ndt_idx` (`id_ndt` ASC) VISIBLE,
  CONSTRAINT `lsnql_nd`
    FOREIGN KEY (`id`)
    REFERENCES `nanocovax`.`ttnguoidung` (`id`),
  CONSTRAINT `lsnql_ndt`
    FOREIGN KEY (`id_ndt`)
    REFERENCES `nanocovax`.`noidieutri` (`id_ndt`),
  CONSTRAINT `lsnql_nyp`
    FOREIGN KEY (`id_nyp`)
    REFERENCES `nanocovax`.`nhuyeupham` (`id_nyp`),
  CONSTRAINT `lsnql_tk`
    FOREIGN KEY (`id_nql`)
    REFERENCES `nanocovax`.`taikhoan` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`lichsuthanhtoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`lichsuthanhtoan` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`lichsuthanhtoan` (
  `sohd` CHAR(11) NOT NULL,
  `thoigian` DATETIME NOT NULL,
  `sotien` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sohd`, `thoigian`),
  CONSTRAINT `lsttoan_hd`
    FOREIGN KEY (`sohd`)
    REFERENCES `nanocovax`.`hoadon` (`sohd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`lichsutrangthai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`lichsutrangthai` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`lichsutrangthai` (
  `id` VARCHAR(12) NOT NULL,
  `thoigian` DATETIME NOT NULL,
  `trangthai` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `lstthai_nd`
    FOREIGN KEY (`id`)
    REFERENCES `nanocovax`.`ttnguoidung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nanocovax`.`lienquan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nanocovax`.`lienquan` ;

CREATE TABLE IF NOT EXISTS `nanocovax`.`lienquan` (
  `id` VARCHAR(12) NOT NULL,
  `id_lienquan` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`, `id_lienquan`),
  INDEX `lq_nd2_idx` (`id_lienquan` ASC) VISIBLE,
  CONSTRAINT `lq_nd1`
    FOREIGN KEY (`id`)
    REFERENCES `nanocovax`.`ttnguoidung` (`id`),
  CONSTRAINT `lq_nd2`
    FOREIGN KEY (`id_lienquan`)
    REFERENCES `nanocovax`.`ttnguoidung` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
